"""Tests for spotify_playlist_manager.logging_config.

Covers the redaction filter (messages, tracebacks, argv masking),
the structured JSON formatter, the human-readable formatter, log_event,
and a basic setup_logging smoke test.
"""

from __future__ import annotations

import json
import logging
import sys
import traceback

import pytest

from spotify_playlist_manager.logging_config import (
    HumanReadableFormatter,
    RedactionFilter,
    StructuredJsonFormatter,
    log_event,
    setup_logging,
)


# ---------------------------------------------------------------------------
# RedactionFilter
# ---------------------------------------------------------------------------


class TestRedactionFilter:
    """Mask secrets in messages, exc_text, stack_info, and extra fields."""

    def setup_method(self) -> None:
        self.filt = RedactionFilter()

    def _make_record(
        self,
        msg: str,
        *,
        exc_info: tuple | None = None,
        extra: dict | None = None,
    ) -> logging.LogRecord:
        record = logging.LogRecord(
            name="spm.test",
            level=logging.INFO,
            pathname="",
            lineno=0,
            msg=msg,
            args=(),
            exc_info=exc_info,
        )
        if extra:
            for k, v in extra.items():
                setattr(record, k, v)
        return record

    # -- password in message --

    def test_masks_password_in_message(self) -> None:
        rec = self._make_record("librespot started --password hunter2 --name kitchen")
        self.filt.filter(rec)
        assert "hunter2" not in rec.msg
        assert "[REDACTED]" in rec.msg

    def test_masks_client_secret(self) -> None:
        rec = self._make_record("client_secret=abc123def456")
        self.filt.filter(rec)
        assert "abc123def456" not in rec.msg
        assert "[REDACTED]" in rec.msg

    def test_masks_access_token(self) -> None:
        rec = self._make_record("access_token: Bearer eyJhbGciOiJIUzI1NiJ9.test.signature")
        self.filt.filter(rec)
        assert "eyJhbGci" not in rec.msg
        assert "[REDACTED]" in rec.msg

    def test_masks_bearer_token(self) -> None:
        rec = self._make_record("Authorization: Bearer BQDj1234567890abcdef")
        self.filt.filter(rec)
        assert "BQDj1234567890" not in rec.msg
        assert "[REDACTED]" in rec.msg

    # -- password in extra fields (list of args, like a subprocess argv) --

    def test_masks_password_in_extra_fields_list(self) -> None:
        """List extra fields with --password + value pairs are redacted."""
        rec = self._make_record(
            "device started",
            extra={"cmd": ["librespot", "--password", "s3cret", "--name", "kitchen"]},
        )
        self.filt.filter(rec)
        cmd = getattr(rec, "cmd")
        assert cmd == ["librespot", "--password", "[REDACTED]", "--name", "kitchen"]
        assert "s3cret" not in str(cmd)

    def test_masks_password_in_extra_fields_string(self) -> None:
        """String extra fields with --password + value are redacted."""
        rec = self._make_record(
            "device started",
            extra={"cmd_str": "librespot --password s3cret --name kitchen"},
        )
        self.filt.filter(rec)
        assert "s3cret" not in getattr(rec, "cmd_str", "")

    # -- exc_info / traceback redaction --

    def test_masks_secret_in_exception_message(self) -> None:
        try:
            raise ValueError("token Bearer abcdef123456abcdef123456abcdef123456 failed")
        except ValueError:
            exc_info = sys.exc_info()

        rec = self._make_record("auth failed", exc_info=exc_info)
        self.filt.filter(rec)

        # exc_text is generated by the filter from exc_info, then redacted.
        assert rec.exc_text is not None
        assert "abcdef123456" not in rec.exc_text
        assert "[REDACTED]" in rec.exc_text

    def test_masks_secret_in_message_with_exc_info(self) -> None:
        """Redaction also applies to the main message when exc_info is present."""
        try:
            raise RuntimeError("something broke")
        except RuntimeError:
            exc_info = sys.exc_info()

        rec = self._make_record(
            "client_secret=supersecret12345678 failed",
            exc_info=exc_info,
        )
        self.filt.filter(rec)
        assert "supersecret12345678" not in rec.msg
        assert "[REDACTED]" in rec.msg

    # -- argv masking --

    def test_redact_argv_masks_password_value(self) -> None:
        argv = ["librespot", "--name", "kitchen", "--password", "mysecret", "-v"]
        result = RedactionFilter.redact_argv(argv)
        assert result == ["librespot", "--name", "kitchen", "--password", "[REDACTED]", "-v"]
        assert "mysecret" not in " ".join(result)

    def test_redact_argv_no_password(self) -> None:
        argv = ["librespot", "--name", "kitchen", "--backend", "pulseaudio"]
        result = RedactionFilter.redact_argv(argv)
        assert result == argv

    def test_redact_argv_empty(self) -> None:
        assert RedactionFilter.redact_argv([]) == []


# ---------------------------------------------------------------------------
# StructuredJsonFormatter
# ---------------------------------------------------------------------------


class TestStructuredJsonFormatter:
    """JSON formatter produces one JSON line per record with UTC timestamps."""

    def setup_method(self) -> None:
        self.fmt = StructuredJsonFormatter()

    def _emit(self, logger_name: str, msg: str, **extra: object) -> dict:
        record = logging.LogRecord(
            name=logger_name,
            level=logging.INFO,
            pathname="",
            lineno=0,
            msg=msg,
            args=(),
            exc_info=None,
        )
        for k, v in extra.items():
            setattr(record, k, v)
        line = self.fmt.format(record)
        return json.loads(line)

    def test_basic_fields(self) -> None:
        doc = self._emit("spotify_playlist_manager.api", "GET /v1/me")
        assert doc["level"] == "INFO"
        assert doc["logger"] == "spotify_playlist_manager.api"
        assert doc["event"] == "GET /v1/me"
        assert doc["timestamp"].endswith("Z")

    def test_custom_extra_fields(self) -> None:
        doc = self._emit(
            "spotify_playlist_manager.user",
            "tracks.add",
            playlist_id="abc123",
            track_count=5,
        )
        assert doc["playlist_id"] == "abc123"
        assert doc["track_count"] == 5

    def test_exception_included(self) -> None:
        try:
            raise ValueError("bad input")
        except ValueError:
            exc_info = sys.exc_info()

        record = logging.LogRecord(
            name="spm",
            level=logging.ERROR,
            pathname="",
            lineno=0,
            msg="something broke",
            args=(),
            exc_info=exc_info,
        )
        line = self.fmt.format(record)
        doc = json.loads(line)
        assert doc["exception"]["type"] == "ValueError"
        assert doc["exception"]["message"] == "bad input"
        assert "traceback" in doc["exception"]

    def test_non_serialisable_value_coerced(self) -> None:
        class Custom:
            def __str__(self) -> str:
                return "custom_obj"

        doc = self._emit("spm", "test", custom=Custom())
        assert doc["custom"] == "custom_obj"

    def test_list_and_dict_fields(self) -> None:
        doc = self._emit(
            "spm",
            "test",
            uris=["spotify:track:aaa", "spotify:track:bbb"],
            meta={"key": "value"},
        )
        assert doc["uris"] == ["spotify:track:aaa", "spotify:track:bbb"]
        assert doc["meta"] == {"key": "value"}


# ---------------------------------------------------------------------------
# HumanReadableFormatter
# ---------------------------------------------------------------------------


class TestHumanReadableFormatter:
    """Human-readable formatter for stderr console output."""

    def setup_method(self) -> None:
        self.fmt = HumanReadableFormatter()

    def test_basic_format(self) -> None:
        record = logging.LogRecord(
            name="spotify_playlist_manager.api",
            level=logging.WARNING,
            pathname="",
            lineno=0,
            msg="rate limited",
            args=(),
            exc_info=None,
        )
        line = self.fmt.format(record)
        assert "WARNING" in line
        assert "spm.api" in line
        assert "rate limited" in line
        # Timestamp in HH:MM:SS format.
        assert "[" in line and "]" in line

    def test_exception_appended_short(self) -> None:
        try:
            raise RuntimeError("boom")
        except RuntimeError:
            exc_info = sys.exc_info()

        record = logging.LogRecord(
            name="spotify_playlist_manager",
            level=logging.ERROR,
            pathname="",
            lineno=0,
            msg="failed",
            args=(),
            exc_info=exc_info,
        )
        line = self.fmt.format(record)
        assert "RuntimeError" in line
        assert "boom" in line


# ---------------------------------------------------------------------------
# log_event
# ---------------------------------------------------------------------------


class TestLogEvent:
    """log_event passes extra fields through to the record."""

    def test_log_event_with_string_logger(self, caplog: pytest.LogCaptureFixture) -> None:
        with caplog.at_level(logging.INFO, logger="spotify_playlist_manager.test"):
            log_event("spotify_playlist_manager.test", "hello", key="value")
        assert len(caplog.records) == 1
        assert caplog.records[0].getMessage() == "hello"
        assert getattr(caplog.records[0], "key") == "value"

    def test_log_event_with_logger_instance(
        self, caplog: pytest.LogCaptureFixture
    ) -> None:
        logger = logging.getLogger("spotify_playlist_manager.test_inst")
        with caplog.at_level(logging.INFO, logger=logger.name):
            log_event(logger, "event here", count=42)
        assert len(caplog.records) == 1
        assert caplog.records[0].getMessage() == "event here"
        assert getattr(caplog.records[0], "count") == 42


# ---------------------------------------------------------------------------
# setup_logging smoke test
# ---------------------------------------------------------------------------


class TestSetupLogging:
    """Basic smoke test: setup_logging runs without error and handlers attach."""

    def test_smoke(self, tmp_path: object) -> None:
        from pathlib import Path

        log_file = Path(str(tmp_path)) / "test.log"
        setup_logging(
            level="DEBUG",
            log_file=log_file,
            file_level="DEBUG",
            console=False,
        )
        logger = logging.getLogger("spotify_playlist_manager")
        # Should have exactly one handler (the file handler).
        assert len(logger.handlers) == 1
        # Write something.
        logger.info("smoke test", extra={"foo": "bar"})
        # Flush handlers.
        for h in logger.handlers:
            h.flush()
        # File should contain a JSON line.
        content = log_file.read_text()
        doc = json.loads(content.strip())
        assert doc["event"] == "smoke test"
        assert doc["foo"] == "bar"

    def test_idempotent(self, tmp_path: object) -> None:
        """Calling setup_logging twice doesn't duplicate handlers."""
        from pathlib import Path

        log_file = Path(str(tmp_path)) / "test.log"
        setup_logging(level="INFO", log_file=log_file, console=False)
        setup_logging(level="INFO", log_file=log_file, console=False)
        logger = logging.getLogger("spotify_playlist_manager")
        # Only one file handler (plus maybe NullHandler from __init__).
        file_handlers = [
            h for h in logger.handlers if isinstance(h, logging.handlers.RotatingFileHandler)
        ]
        assert len(file_handlers) == 1
